[workspace]
resolver = "3"
members = ["benchmarks", "borrows","boxes", "concurrency", "concurrent-data-structures", "fake-test", "iter", "mem", "pointers", "sizes", "slices", "slow-hash", "vector-capacity"]
